/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Argophloia(props) {
  const { nodes, materials } = useGLTF('/models/plants/Argophloia.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.柱体.geometry} material={materials['材质.001']} position={[0.04, 7.03, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.42, -7, -0.42]} />
      <mesh geometry={nodes.平面.geometry} material={materials.材质} position={[0.7, 1.95, 0.1]} scale={[2, 1, 0.55]} />
      <mesh geometry={nodes.平面001.geometry} material={materials.材质} position={[0.15, 1.95, 0.2]} rotation={[-1.95, 1.42, 1.99]} scale={[2.15, 1.07, 0.59]} />
      <mesh geometry={nodes.平面002.geometry} material={materials.材质} position={[0.15, 1.95, 0.2]} rotation={[2.95, -0.2, -3.03]} scale={[2.39, 1.2, 0.66]} />
      <mesh geometry={nodes.平面003.geometry} material={materials.材质} position={[0.15, 1.95, 0.2]} rotation={[-1.67, -1.19, -1.47]} scale={[2.39, 1.2, 0.66]} />
      <mesh geometry={nodes.平面004.geometry} material={materials.材质} position={[0.67, 2.9, 0.2]} rotation={[-0.01, -0.25, 0.07]} scale={[1.84, 0.92, 0.51]} />
      <mesh geometry={nodes.平面006.geometry} material={materials.材质} position={[0.16, 2.86, 0.17]} rotation={[2.94, 0.05, -3.04]} scale={[2.2, 1.1, 0.6]} />
      <mesh geometry={nodes.平面007.geometry} material={materials.材质} position={[0.16, 2.86, 0.17]} rotation={[-2.3, -1.15, -2.13]} scale={[2.2, 1.1, 0.6]} />
      <mesh geometry={nodes.平面008.geometry} material={materials.材质} position={[0.79, 3.68, 0.38]} rotation={[-0.17, -0.49, 0.03]} scale={[1.74, 0.87, 0.48]} />
      <mesh geometry={nodes.平面009.geometry} material={materials.材质} position={[0.33, 3.64, 0.24]} rotation={[-0.55, 1.11, 0.38]} scale={[1.87, 0.94, 0.52]} />
      <mesh geometry={nodes.平面011.geometry} material={materials.材质} position={[0.33, 3.64, 0.24]} rotation={[-2.68, -0.95, -2.4]} scale={[2.09, 1.04, 0.57]} />
      <mesh geometry={nodes.平面012.geometry} material={materials.材质} position={[0.81, 4.45, 0.48]} rotation={[-0.31, -0.71, -0.07]} scale={[1.74, 0.87, 0.48]} />
      <mesh geometry={nodes.平面013.geometry} material={materials.材质} position={[0.39, 4.41, 0.24]} rotation={[-0.42, 0.91, 0.12]} scale={[1.87, 0.94, 0.52]} />
      <mesh geometry={nodes.平面014.geometry} material={materials.材质} position={[0.39, 4.41, 0.24]} rotation={[2.64, 0.49, -2.82]} scale={[2.09, 1.04, 0.57]} />
      <mesh geometry={nodes.平面015.geometry} material={materials.材质} position={[0.39, 4.41, 0.24]} rotation={[-2.84, -0.72, -2.5]} scale={[2.09, 1.04, 0.57]} />
      <mesh geometry={nodes.平面016.geometry} material={materials.材质} position={[0.4, 5.13, -0.2]} rotation={[0.17, 0.71, -0.02]} scale={[1.59, 0.79, 0.44]} />
      <mesh geometry={nodes.平面017.geometry} material={materials.材质} position={[0.13, 5.08, 0.14]} rotation={[-2.79, 0.8, 3.05]} scale={[1.7, 0.85, 0.47]} />
      <mesh geometry={nodes.平面018.geometry} material={materials.材质} position={[0.13, 5.08, 0.14]} rotation={[3.02, -0.9, 3.08]} scale={[1.9, 0.95, 0.52]} />
      <mesh geometry={nodes.平面019.geometry} material={materials.材质} position={[0.13, 5.08, 0.14]} rotation={[-0.42, -0.81, -0.24]} scale={[1.9, 0.95, 0.52]} />
      <mesh geometry={nodes.平面020.geometry} material={materials.材质} position={[0.29, 6.01, -0.27]} rotation={[0.13, 0.62, -0.05]} scale={[1.43, 0.72, 0.39]} />
      <mesh geometry={nodes.平面021.geometry} material={materials.材质} position={[0.02, 5.99, 0.02]} rotation={[-2.87, 0.89, 3.07]} scale={[1.54, 0.77, 0.42]} />
      <mesh geometry={nodes.平面023.geometry} material={materials.材质} position={[0.02, 5.99, 0.02]} rotation={[-0.56, -0.87, -0.35]} scale={[1.71, 0.86, 0.47]} />
      <mesh geometry={nodes.平面024.geometry} material={materials.材质} position={[-0.24, 6.73, -0.69]} rotation={[-2.62, 1.56, 2.82]} scale={[1.43, 0.72, 0.39]} />
      <mesh geometry={nodes.平面025.geometry} material={materials.材质} position={[-0.16, 6.66, -0.3]} rotation={[-2.81, -0.07, -3.1]} scale={[1.54, 0.77, 0.42]} />
      <mesh geometry={nodes.平面026.geometry} material={materials.材质} position={[-0.16, 6.66, -0.3]} rotation={[0.91, -1.28, 0.85]} scale={[1.71, 0.86, 0.47]} />
      <mesh geometry={nodes.平面028.geometry} material={materials.材质} position={[-0.29, 7.61, -0.76]} rotation={[0.33, 0.99, -0.23]} scale={[1.35, 0.67, 0.37]} />
      <mesh geometry={nodes.平面029.geometry} material={materials.材质} position={[-0.43, 7.58, -0.42]} rotation={[-2.92, 0.52, -3.04]} scale={[1.45, 0.72, 0.4]} />
      <mesh geometry={nodes.平面030.geometry} material={materials.材质} position={[-0.43, 7.58, -0.42]} rotation={[3.08, -1.21, -3.13]} scale={[1.61, 0.81, 0.44]} />
      <mesh geometry={nodes.平面031.geometry} material={materials.材质} position={[-0.43, 7.58, -0.42]} rotation={[-0.38, -0.5, -0.17]} scale={[1.61, 0.81, 0.44]} />
      <mesh geometry={nodes.平面032.geometry} material={materials.材质} position={[-0.34, 8.52, -0.81]} rotation={[0.27, 0.54, -0.1]} scale={[1.13, 0.57, 0.31]} />
      <mesh geometry={nodes.平面033.geometry} material={materials.材质} position={[-0.57, 8.49, -0.59]} rotation={[-2.81, 0.97, 3.13]} scale={[1.22, 0.61, 0.33]} />
      <mesh geometry={nodes.平面034.geometry} material={materials.材质} position={[-0.57, 8.49, -0.59]} rotation={[-3.1, -0.76, -3.04]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面035.geometry} material={materials.材质} position={[-0.57, 8.49, -0.59]} rotation={[-0.56, -0.89, -0.49]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面036.geometry} material={materials.材质} position={[-0.34, 9.36, -0.96]} rotation={[0.27, 0.54, -0.1]} scale={[1.13, 0.57, 0.31]} />
      <mesh geometry={nodes.平面037.geometry} material={materials.材质} position={[-0.57, 9.34, -0.75]} rotation={[-2.81, 0.97, 3.13]} scale={[1.22, 0.61, 0.33]} />
      <mesh geometry={nodes.平面038.geometry} material={materials.材质} position={[-0.57, 9.34, -0.75]} rotation={[-3.1, -0.76, -3.04]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面039.geometry} material={materials.材质} position={[-0.57, 9.34, -0.75]} rotation={[-0.56, -0.89, -0.49]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面040.geometry} material={materials.材质} position={[-0.29, 10.15, -0.63]} rotation={[0.07, 0.05, 0.2]} scale={[1.13, 0.57, 0.31]} />
      <mesh geometry={nodes.平面041.geometry} material={materials.材质} position={[-0.59, 10.09, -0.56]} rotation={[-1.8, 1.22, 1.91]} scale={[1.22, 0.61, 0.33]} />
      <mesh geometry={nodes.平面042.geometry} material={materials.材质} position={[-0.59, 10.09, -0.56]} rotation={[2.98, -0.21, 3.05]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面043.geometry} material={materials.材质} position={[-0.59, 10.09, -0.56]} rotation={[-1.44, -1.39, -1.3]} scale={[1.36, 0.68, 0.37]} />
      <mesh geometry={nodes.平面044.geometry} material={materials.材质} position={[-0.37, 10.93, -0.29]} rotation={[0.07, -0.3, 0.22]} scale={[0.97, 0.49, 0.27]} />
      <mesh geometry={nodes.平面045.geometry} material={materials.材质} position={[-0.63, 10.88, -0.32]} rotation={[-0.95, 1.14, 0.99]} scale={[1.05, 0.52, 0.29]} />
      <mesh geometry={nodes.平面047.geometry} material={materials.材质} position={[-0.63, 10.88, -0.32]} rotation={[-2.63, -1.2, -2.53]} scale={[1.17, 0.58, 0.32]} />
      <mesh geometry={nodes.平面048.geometry} material={materials.材质} position={[-0.11, 11.74, -0.16]} rotation={[0.13, -0.68, 0.22]} scale={[0.97, 0.49, 0.27]} />
      <mesh geometry={nodes.平面049.geometry} material={materials.材质} position={[-0.35, 11.7, -0.28]} rotation={[-0.44, 0.87, 0.48]} scale={[1.05, 0.52, 0.29]} />
      <mesh geometry={nodes.平面050.geometry} material={materials.材质} position={[-0.35, 11.7, -0.28]} rotation={[3.02, 0.5, -3.08]} scale={[1.17, 0.58, 0.32]} />
      <mesh geometry={nodes.平面051.geometry} material={materials.材质} position={[-0.35, 11.7, -0.28]} rotation={[-2.77, -0.84, -2.76]} scale={[1.17, 0.58, 0.32]} />
      <mesh geometry={nodes.平面052.geometry} material={materials.材质} position={[0, 12.48, -0.04]} rotation={[0.34, -0.88, 0.35]} scale={[0.8, 0.4, 0.22]} />
      <mesh geometry={nodes.平面053.geometry} material={materials.材质} position={[-0.17, 12.45, -0.19]} rotation={[-0.29, 0.65, 0.42]} scale={[0.86, 0.43, 0.24]} />
      <mesh geometry={nodes.平面054.geometry} material={materials.材质} position={[-0.17, 12.45, -0.19]} rotation={[-3.13, 0.72, -3.12]} scale={[0.96, 0.48, 0.26]} />
      <mesh geometry={nodes.平面055.geometry} material={materials.材质} position={[-0.17, 12.45, -0.19]} rotation={[-2.76, -0.65, -2.92]} scale={[0.96, 0.48, 0.26]} />
      <mesh geometry={nodes.平面056.geometry} material={materials.材质} position={[-0.17, 13.06, 0.02]} rotation={[1.23, -1.36, 1.31]} scale={[0.47, 0.23, 0.13]} />
      <mesh geometry={nodes.平面057.geometry} material={materials.材质} position={[-0.21, 13.04, -0.11]} rotation={[-0.23, 0.08, 0.25]} scale={[0.5, 0.25, 0.14]} />
      <mesh geometry={nodes.平面058.geometry} material={materials.材质} position={[-0.21, 13.04, -0.11]} rotation={[3.1, 1.31, -3.06]} scale={[0.56, 0.28, 0.15]} />
      <mesh geometry={nodes.平面059.geometry} material={materials.材质} position={[-0.21, 13.04, -0.11]} rotation={[-2.84, -0.09, -3.11]} scale={[0.56, 0.28, 0.15]} />
      <mesh geometry={nodes.平面060.geometry} material={materials.材质} position={[0.04, 13.58, -0.05]} rotation={[0.34, -0.88, 0.35]} scale={[0.35, 0.17, 0.1]} />
      <mesh geometry={nodes.平面061.geometry} material={materials.材质} position={[-0.03, 13.57, -0.12]} rotation={[-0.29, 0.65, 0.42]} scale={[0.37, 0.19, 0.1]} />
      <mesh geometry={nodes.平面062.geometry} material={materials.材质} position={[-0.03, 13.57, -0.12]} rotation={[-3.13, 0.72, -3.12]} scale={[0.42, 0.21, 0.11]} />
      <mesh geometry={nodes.平面063.geometry} material={materials.材质} position={[-0.03, 13.57, -0.12]} rotation={[-2.76, -0.65, -2.92]} scale={[0.42, 0.21, 0.11]} />
    </group>
  )
}

useGLTF.preload('/Argophloia.glb')
