/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CooktownOrchid(props) {
  const { nodes, materials } = useGLTF('/models/plants/CooktownOrchid.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.33, 6.5, -0.05]} rotation={[-0.82, -0.31, -1.58]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[3.17, 5.85, 3.28]} rotation={[-0.82, -0.31, -1.58]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[2.93, 8.35, 2.61]} rotation={[0.99, -0.27, -0.22]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-1.64, 8.62, 1.92]} rotation={[0.63, 1.03, 0.05]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-2.02, 8.58, -0.78]} rotation={[2.21, 0.11, 2.55]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[0.47, 8.59, -0.89]} rotation={[2.23, 0.94, -2.92]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[1.03, 6.99, -1.54]} rotation={[2.73, -0.68, 3.01]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-1.37, 6.42, -1.24]} rotation={[2.73, -0.68, 3.01]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-1.94, 6.96, -2.27]} rotation={[1.52, 1.39, -3.05]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-3.18, 7.26, 2.24]} rotation={[0.33, 0.5, 1.06]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-2.13, 6.57, 3.94]} rotation={[-1.3, 0.87, 1.79]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[1.26, 7.1, 3.85]} rotation={[-1.19, 1.25, 1.2]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[2.91, 8.44, 0.49]} rotation={[-2.53, -0.77, -1.94]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[2.33, 4.95, -1.92]} rotation={[-2.34, -0.16, -1.11]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[0.59, 5.44, -2.67]} rotation={[0.97, 1.04, -2.58]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <group position={[-0.51, 4.99, 4.95]} rotation={[-1.55, -0.99, 3.05]} scale={[0.36, 0.18, 0.1]}>
        <mesh geometry={nodes.平面_1.geometry} material={materials.材质} />
        <mesh geometry={nodes.平面_2.geometry} material={materials['材质.002']} />
      </group>
      <mesh geometry={nodes.立方体.geometry} material={materials['材质.007']} position={[-2.06, 6.24, 1.4]} />
      <mesh geometry={nodes.立方体001.geometry} material={materials['材质.007']} position={[-0.95, 5.63, 3.44]} />
      <mesh geometry={nodes.立方体002.geometry} material={materials['材质.007']} position={[1.96, 5.87, 2.92]} />
      <mesh geometry={nodes.立方体003.geometry} material={materials['材质.007']} position={[1.16, 5.67, -1.39]} />
      <mesh geometry={nodes.立方体004.geometry} material={materials['材质.007']} position={[-1.18, 6.34, -1.13]} />
      <mesh geometry={nodes.立方体005.geometry} material={materials['材质.007']} position={[3.12, 6.45, 0.12]} />
      <mesh geometry={nodes.立方体006.geometry} material={materials['材质.007']} position={[1.65, 7.23, 1.42]} scale={1.21} />
      <mesh geometry={nodes.立方体008.geometry} material={materials['材质.007']} position={[-0.76, 7.42, 0.47]} scale={1.21} />
    </group>
  )
}

useGLTF.preload('/CooktownOrchid.glb')
