/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Grass(props) {
  const { nodes, materials } = useGLTF('models/plants/Grass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.棱角球.geometry} material={materials['材质.003']} position={[0, 1.96, 0.09]} rotation={[0, -0.58, 0]} scale={[0.15, 0.75, 0.15]} />
      <mesh geometry={nodes.柱体.geometry} material={materials['材质.002']} position={[0.03, 0.7, 0.08]} rotation={[-Math.PI, 0.58, -Math.PI]} scale={[0.01, 0.59, 0.02]} />
      <mesh geometry={nodes.平面007.geometry} material={materials['材质.001']} position={[0.02, 0.08, -0.03]} rotation={[Math.PI, -0.68, Math.PI]} scale={[0.73, 0.37, 0.2]} />
    </group>
  )
}

useGLTF.preload('/Grass.glb')
