/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Jacaranda(props) {
  const { nodes, materials } = useGLTF('/models/plants/Jacaranda.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.棱角球001.geometry} material={materials.tree} position={[1.58, 5.08, -1.9]} />
    </group>
  )
}

useGLTF.preload('/Jacaranda.glb')
