/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Redgumtree1(props) {
  const { nodes, materials } = useGLTF('/models/plants/Redgumtree1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.2, 4.43, -0.44]} scale={-0.73}>
        <mesh geometry={nodes.立方体010.geometry} material={materials.材质} />
        <mesh geometry={nodes.立方体010_1.geometry} material={materials['材质.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Redgumtree1.glb')
