/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Viminalis(props) {
  const { nodes, materials } = useGLTF('/models/plants/Viminalis.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.棱角球002.geometry} material={materials['材质.008']} position={[0.36, 7.23, -1.74]} scale={2.57} />
      <mesh geometry={nodes.立方体019.geometry} material={materials['材质.012']} position={[2.38, 7.48, 3.79]} rotation={[-2.59, -1.07, -2.21]} scale={0.53} />
    </group>
  )
}

useGLTF.preload('/Viminalis.glb')
