/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BrisbaneMap(props) {
    const { nodes, materials } = useGLTF('/models/maps/BrisbaneMap.glb');
    
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.贝塞尔曲线.geometry} material={materials.材质} position={[-0.45, 2.06, -0.7]} />
            <mesh geometry={nodes.贝塞尔曲线001.geometry} material={materials['材质.001']} position={[-0.45, 2.11, -0.7]} />
            <mesh geometry={nodes.贝塞尔曲线002.geometry} material={materials.材质} position={[-0.5, 2.06, -0.7]} />
            <mesh geometry={nodes.贝塞尔曲线003.geometry} material={materials['材质.001']} position={[-0.45, 2.12, -0.7]} />
            <mesh geometry={nodes.立方体.geometry} material={materials['材质.002']} position={[8.04, 2.22, -2.64]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体001.geometry} material={materials['材质.002']} position={[8.21, 2.22, -2.64]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体006.geometry} material={materials['材质.002']} position={[-1.22, 2.22, 1.89]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体007.geometry} material={materials['材质.002']} position={[-1.05, 2.22, 1.89]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体010.geometry} material={materials['材质.002']} position={[-0.34, 2.22, -4.88]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体011.geometry} material={materials['材质.002']} position={[-0.16, 2.22, -4.88]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体014.geometry} material={materials['材质.002']} position={[3.37, 2.22, -1.27]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体015.geometry} material={materials['材质.002']} position={[3.54, 2.22, -1.27]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体018.geometry} material={materials['材质.002']} position={[-2.59, 2.25, -0.86]} rotation={[-0.05, -0.7, 0.04]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体019.geometry} material={materials['材质.002']} position={[-2.71, 2.26, -0.72]} rotation={[3.1, 0.72, 3.1]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体002.geometry} material={materials['材质.003']} position={[8.13, 2.2, -0.42]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体003.geometry} material={materials['材质.003']} position={[7.95, 2.2, -0.42]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体008.geometry} material={materials['材质.003']} position={[-1.13, 2.2, 4.11]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体009.geometry} material={materials['材质.003']} position={[-1.31, 2.2, 4.11]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体012.geometry} material={materials['材质.003']} position={[-0.21, 2.2, -2.32]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体013.geometry} material={materials['材质.003']} position={[-0.39, 2.2, -2.32]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体016.geometry} material={materials['材质.003']} position={[3.46, 2.2, 0.96]} rotation={[Math.PI, -1.54, Math.PI]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体017.geometry} material={materials['材质.003']} position={[3.28, 2.2, 0.96]} rotation={[0, 1.56, 0]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体020.geometry} material={materials['材质.003']} position={[-4.37, 2.09, -2.2]} rotation={[3.1, 0.72, 3.1]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体021.geometry} material={materials['材质.003']} position={[-4.25, 2.08, -2.33]} rotation={[-0.05, -0.7, 0.04]} scale={[0.11, 0.11, 0.09]} />
            <mesh geometry={nodes.立方体004.geometry} material={materials['材质.005']} position={[1.41, 2.37, -6.15]} rotation={[0, -0.1, 0]} scale={[1, 0.24, 0.24]} />
            <mesh geometry={nodes.立方体022.geometry} material={materials['材质.005']} position={[5.9, 2.37, 1.76]} rotation={[0, 0.35, 0]} scale={[1, 0.24, 0.24]} />
            <mesh geometry={nodes.立方体023.geometry} material={materials['材质.005']} position={[-5.27, 2.37, 5.8]} rotation={[-Math.PI, 0.6, -Math.PI]} scale={[1, 0.24, 0.24]} />
            <mesh geometry={nodes.立方体005.geometry} material={materials['材质.004']} position={[5.54, 2.21, 3.2]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体024.geometry} material={materials['材质.004']} position={[2.12, 2.21, -4.82]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体025.geometry} material={materials['材质.004']} position={[-0.54, 2.21, -0.95]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体026.geometry} material={materials['材质.004']} position={[0.49, 2.21, 1.03]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体027.geometry} material={materials['材质.004']} position={[-2.91, 2.21, 5.37]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体028.geometry} material={materials['材质.004']} position={[-4.58, 2.21, -5.55]} scale={[0.28, 0.1, 0.28]} />
            <mesh geometry={nodes.立方体029.geometry} material={materials['材质.004']} position={[6.64, 2.21, -6.89]} scale={[0.28, 0.1, 0.28]} />
        </group>
    )
}

useGLTF.preload('/BrisbaneMap.glb')
