/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ocean(props) {
  const { nodes, materials } = useGLTF('/models/maps/Ocean.glb')
  return (
      <group {...props} dispose={null} scale={20}>
      <mesh geometry={nodes['0cean'].geometry} material={materials.Ocean} position={[0, 0, 0]} />
      <mesh geometry={nodes['0cean001'].geometry} material={materials.Ocean} position={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Ocean.glb')
